<a href="https://colab.research.google.com/github/debojit11/Deep_Learning_Pytorch/blob/main/practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
# Scalar (0D Tensor)
scalar = torch.tensor(5)
scalar

tensor(5)

In [ ]:
# Vector (1D Tensor)
vector = torch.tensor([1,2,3])
vector

tensor([1, 2, 3])

In [ ]:
# Matrix (2D Tensor)
matrix = torch.tensor([[1,2], [3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [ ]:
# 3D Tensor
tensor3d = torch.tensor([[[1,2], [3,4], [5,6]]])
tensor3d

tensor([[[1, 2],
         [3, 4],
         [5, 6]]])

In [ ]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

In [ ]:
#addition
a+b

tensor([5, 7, 9])

In [ ]:
#subtraction
a-b

tensor([-3, -3, -3])

In [ ]:
# multiplication
a*b

tensor([ 4, 10, 18])

In [ ]:
# division
a/b

tensor([0.2500, 0.4000, 0.5000])

In [ ]:
A= torch.tensor([[1,2], [3,4]])
B= torch.tensor([[5,6], [7,8]])

In [ ]:
# matrix multiplication
torch.mm(A,B) # or use A @ B

tensor([[19, 22],
        [43, 50]])

In [ ]:
x = torch.tensor(3.0, requires_grad=True) # Enable autograd

In [ ]:
y = x**2    # y = x^2
y.backward()  # Compute gradient, dy/dx
x.grad

tensor(6.)

In [ ]:
x = torch.tensor(3.0, requires_grad=True) # Enable autograd
y = x**2    # y = x^2
z = 3*y + 2  # z = 3y + 2
# Compute gradient
z.backward()
x.grad

tensor(18.)

In [ ]:
i = torch.tensor([[1,2,3], [4,5,6]])
i

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# Transpose the matrix
i_T = i.T     # or A.transpose(0, 1)
i_T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

**If you have a 3D tensor (batch of matrices), use .permute() instead.**

# **Exercise**



1.   **Create a 4x4 tensor with random values. Find its transpose.**


2.   **Compute the gradient of f(x)= 4x^3 + 3x^2 - 5x + 2 at x=2 using PyTorch’s autograd**


3.   **Multiply a 2x3 tensor with a 3x2 tensor and print the result.**


In [ ]:
tensor1 = torch.rand(4,4)
tensor1

tensor([[0.1458, 0.5640, 0.6568, 0.3524],
        [0.1482, 0.2194, 0.2557, 0.5214],
        [0.0874, 0.5163, 0.3376, 0.7359],
        [0.1704, 0.6663, 0.4750, 0.8656]])

In [ ]:
tensor1.T

tensor([[0.1458, 0.1482, 0.0874, 0.1704],
        [0.5640, 0.2194, 0.5163, 0.6663],
        [0.6568, 0.2557, 0.3376, 0.4750],
        [0.3524, 0.5214, 0.7359, 0.8656]])

In [ ]:
j = torch.tensor(2.0, requires_grad=True)
y = 4*(j**3) + 3*(j**2) - 5*j + 2
y.backward()
j.grad

tensor(55.)

In [ ]:
tensor23 = torch.randint(0,10,(2,3))
tensor23

tensor([[9, 7, 2],
        [0, 6, 5]])

In [ ]:
tensor32 = torch.randint(0,10,(3,2))
tensor32

tensor([[4, 0],
        [1, 7],
        [9, 6]])

In [ ]:
torch.mm(tensor23, tensor32)

tensor([[61, 61],
        [51, 72]])

In [ ]:
a = torch.tensor(5.0, requires_grad=True)

In [ ]:
b = 3*(a**3) - 4*(a**2) + 2*a - 1
b.backward()
a.grad

tensor(187.)

**==========================================================================================================================================================================================================================**

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
# define the network
class SimpleNN(nn.Module):
  def __init__(self):
    super(SimpleNN, self).__init__()
    self.fc1 = nn.Linear(3,4)  # 3 inputs → 4 neurons
    self.fc2 = nn.Linear(4,1)  # 4 → 1 output


  def forward(self,x):
    x = F.relu(self.fc1(x))  # activation after first layer
    x = torch.sigmoid(self.fc2(x))  # sigmoid at output
    return x

In [ ]:
# Initialize network
model = SimpleNN()

In [ ]:
# Dummy input
x = torch.tensor([1.0, 2.0, 3.0])

In [ ]:
# Forward pass
output = model(x)
print(output)

tensor([0.5063], grad_fn=<SigmoidBackward0>)


In [ ]:
# define the network
class basicNN(nn.Module):
  def __init__(self):
    super(basicNN, self).__init__()
    self.fc1 = nn.Linear(2,5)  # 2 inputs → 5 neurons
    self.fc2 = nn.Linear(5,1)  # 5 → 1 output


  def forward(self,x):
    x = F.relu(self.fc1(x))  # activation after first layer
    x = torch.sigmoid(self.fc2(x))  # sigmoid at output
    return x

In [ ]:
model1 = basicNN()

In [ ]:
x = torch.tensor([2.0, -1.0])
output = model1(x)
print(output)

tensor([0.6467], grad_fn=<SigmoidBackward0>)


In [ ]:
print(model1.parameters)

<bound method Module.parameters of basicNN(
  (fc1): Linear(in_features=2, out_features=5, bias=True)
  (fc2): Linear(in_features=5, out_features=1, bias=True)
)>


**==========================================================================================================================================================================================================================**

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

In [ ]:
# Dummy dataset (inputs and binary labels)
X = torch.tensor([[1.0, 2.0],
                  [2.0, -1.0],
                  [-1.0, -2.0],
                  [-2.0, 1.0]])
y = torch.tensor([[1.0], [1.0], [0.0], [0.0]])

In [ ]:
# Simple model
class BinaryClassifier(nn.Module):
  def __init__(self):
    super().__init__()
    self.fc1 = nn.Linear(2, 10) # hidden layer was five earlier, this is for exercise
    self.fc2 = nn.Linear(10, 1)

  def forward(self, x):
    x = torch.relu(self.fc1(x))
    return torch.sigmoid(self.fc2(x))

In [ ]:
model = BinaryClassifier()

In [ ]:
# Loss & Optimizer
criterion = nn.MSELoss() # was BCELoss() earlier, this is for exercise
optimizer = optim.Adam(model.parameters(), lr=0.01)

In [ ]:
# Training loop
for epoch in range(10):
  # forward pass
  outputs = model(X)
  loss = criterion(outputs, y)

  # backward pass
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

  print(f"Epoch : [{epoch}],  Loss : {loss.item():.4f}")

Epoch : [0],  Loss : 0.2698
Epoch : [1],  Loss : 0.2615
Epoch : [2],  Loss : 0.2535
Epoch : [3],  Loss : 0.2457
Epoch : [4],  Loss : 0.2381
Epoch : [5],  Loss : 0.2306
Epoch : [6],  Loss : 0.2232
Epoch : [7],  Loss : 0.2159
Epoch : [8],  Loss : 0.2091
Epoch : [9],  Loss : 0.2024


the loss going down at each epoch is very low

In [ ]:
# Final predictions
print("\nFinal Predictions:")
print(model(X).detach())


Final Predictions:
tensor([[0.6222],
        [0.4930],
        [0.4873],
        [0.3813]])


**==========================================================================================================================================================================================================================**

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:

class SimpleCNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(1, 8, kernel_size=3, stride=1, padding=1)  # Output: 8x28x28
        self.pool = nn.MaxPool2d(2, 2)  # Output: 8x14x14
        self.conv2 = nn.Conv2d(8, 16, 3, 1, 1)  # Output: 16x14x14 → pool → 16x7x7
        self.fc1 = nn.Linear(16*7*7, 64)
        self.fc2 = nn.Linear(64, 10)  # 10 classes for digits

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))  # Conv + ReLU + Pool
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(-1, 16*7*7)  # flatten
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x

In [ ]:
from torchvision import datasets, transforms

In [ ]:
transform = transforms.Compose([transforms.ToTensor()])
train_data = datasets.MNIST(root='data', train=True, download=True, transform=transform)
train_loader = torch.utils.data.DataLoader(train_data, batch_size=32, shuffle=True)

100%|██████████| 9.91M/9.91M [00:00<00:00, 14.9MB/s]
100%|██████████| 28.9k/28.9k [00:00<00:00, 500kB/s]
100%|██████████| 1.65M/1.65M [00:00<00:00, 3.86MB/s]
100%|██████████| 4.54k/4.54k [00:00<00:00, 6.24MB/s]


In [ ]:
model = SimpleCNN()
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [ ]:
for epoch in range(1):
    for images, labels in train_loader:
        output = model(images)
        loss = loss_fn(output, labels)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
    print(f"Epoch [{epoch+1}], Loss: {loss.item():.4f}")

Epoch [1], Loss: 0.0299
