<a href="https://colab.research.google.com/github/debojit11/Deep_Learning_Pytorch/blob/main/practice_day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
# Scalar (0D Tensor)
scalar = torch.tensor(5)
scalar

tensor(5)

In [3]:
# Vector (1D Tensor)
vector = torch.tensor([1,2,3])
vector

tensor([1, 2, 3])

In [4]:
# Matrix (2D Tensor)
matrix = torch.tensor([[1,2], [3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [5]:
# 3D Tensor
tensor3d = torch.tensor([[[1,2], [3,4], [5,6]]])
tensor3d

tensor([[[1, 2],
         [3, 4],
         [5, 6]]])

In [6]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

In [7]:
#addition
a+b

tensor([5, 7, 9])

In [8]:
#subtraction
a-b

tensor([-3, -3, -3])

In [9]:
# multiplication
a*b

tensor([ 4, 10, 18])

In [10]:
# division
a/b

tensor([0.2500, 0.4000, 0.5000])

In [11]:
A= torch.tensor([[1,2], [3,4]])
B= torch.tensor([[5,6], [7,8]])

In [12]:
# matrix multiplication
torch.mm(A,B) # or use A @ B

tensor([[19, 22],
        [43, 50]])

In [13]:
x = torch.tensor(3.0, requires_grad=True) # Enable autograd

In [14]:
y = x**2    # y = x^2
y.backward()  # Compute gradient, dy/dx
x.grad

tensor(6.)

In [14]:
z = 3*y + 2  # z = 3y + 2
# Compute gradient
z.backward()
x.grad

In [16]:
i = torch.tensor([[1,2,3], [4,5,6]])
i

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
# Transpose the matrix
i_T = i.T     # or A.transpose(0, 1)
i_T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

**If you have a 3D tensor (batch of matrices), use .permute() instead.**

# **Exercise**



1.   **Create a 4x4 tensor with random values. Find its transpose.**


2.   **Compute the gradient of f(x)= 4x^3 + 3x^2 - 5x + 2 at x=2 using PyTorch’s autograd**


3.   **Multiply a 2x3 tensor with a 3x2 tensor and print the result.**


In [26]:
tensor1 = torch.rand(4,4)
tensor1

tensor([[0.6623, 0.3536, 0.9863, 0.4299],
        [0.2373, 0.3009, 0.8286, 0.7828],
        [0.5496, 0.0126, 0.4173, 0.5639],
        [0.2522, 0.4258, 0.2093, 0.1315]])

In [27]:
tensor1.T

tensor([[0.6623, 0.2373, 0.5496, 0.2522],
        [0.3536, 0.3009, 0.0126, 0.4258],
        [0.9863, 0.8286, 0.4173, 0.2093],
        [0.4299, 0.7828, 0.5639, 0.1315]])

In [20]:
j = torch.tensor(2.0, requires_grad=True)
y = 4*(j**3) + 3*(j**2) - 5*j + 2
y.backward()
j.grad

tensor(55.)

In [21]:
tensor23 = torch.randint(0,10,(2,3))
tensor23

tensor([[6, 0, 2],
        [9, 1, 3]])

In [22]:
tensor32 = torch.randint(0,10,(3,2))
tensor32

tensor([[3, 0],
        [4, 2],
        [5, 6]])

In [24]:
torch.mm(tensor23, tensor32)

tensor([[28, 12],
        [46, 20]])