<a href="https://colab.research.google.com/github/debojit11/Deep_Learning_Pytorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TENSORS**



*   A torch. Tensor is a multi-dimensional matrix containing elements of a single data type.

*   Similar TO Numpy Arrays, but full Of fun things that make them work better on GPU's (vs regular CPU's).

*   default data type of float32.

*   More suitable for deep learning than a numpy array.



In [1]:
import torch
import numpy as np

# **LISTS**

In [3]:
my_list =[[1,2,3,4],[5,6,7,8]]
my_list

[[1, 2, 3, 4], [5, 6, 7, 8]]

# **NUMPY ARRAYS**

In [4]:
np1 = np.random.rand(3,4)
np1

array([[0.82623609, 0.48900808, 0.80591677, 0.89904476],
       [0.2561183 , 0.96057702, 0.23871827, 0.62235784],
       [0.83621218, 0.29287639, 0.1417866 , 0.95980465]])

In [5]:
np1.dtype

dtype('float64')

# **TENSORS**

In [11]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.8626,  0.9820,  0.1704,  0.8887],
        [ 0.5356, -0.3226, -0.1678,  0.5389],
        [ 0.5588, -1.0223, -0.1442, -0.1079]])

In [12]:
tensor_2d.dtype

torch.float32

In [7]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
# create tensor out of numpy array

In [9]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.8262, 0.4890, 0.8059, 0.8990],
        [0.2561, 0.9606, 0.2387, 0.6224],
        [0.8362, 0.2929, 0.1418, 0.9598]], dtype=torch.float64)