<a href="https://colab.research.google.com/github/debojit11/Deep_Learning_Pytorch/blob/main/Tensor_Operations_Reshape_and_Slice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import torch

In [20]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# Reshape and View

In [22]:
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [23]:
# cannot ndo any other shpae liek (2,6) as it would need 12 items but we have 10 items so wehave to keep in mind about that

In [24]:
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# reshape if we don't know the number of items using -1
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [26]:
# again if we have 15 items and we try to reshape using (2,-1), it will throw error of "shape '[2, -1]' is invalid for input of size 15" but the reshape will work for (3,-1)

In [27]:
# we can also place the -1 at the row initializing part if we dont know what to use

In [28]:
my_torch3 = torch.arange(15)
my_torch3

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
my_torch3 = my_torch3.reshape(-1,5)
my_torch3

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [30]:
# but always remeber to look at the items and then choose the row or column number according to that

In [31]:
my_torch4 = torch.arange(10)
my_torch4

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
my_torch5 = my_torch4.view(2,5)
my_torch5

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

**[Difference between reshape and view](https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch)**  check it out

In [33]:
# with reshape and view, they will update
my_torch6 = torch.arange(10)
my_torch6

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
my_torch7 = my_torch6.reshape(2,5)
my_torch7

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [36]:
my_torch6[1] = 4141
my_torch6

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [37]:
my_torch7

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

## Slices

In [38]:
my_torch8 = torch.arange(10)
my_torch8

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
# grabbing a specific item , not the number 7 but the tensor 7
my_torch8[7]

tensor(7)

In [41]:
my_torch9 = my_torch8.reshape(5,2)
my_torch9

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [42]:
my_torch9[:,1]

tensor([1, 3, 5, 7, 9])

In [43]:
# return column
my_torch9[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])