<a href="https://colab.research.google.com/github/debojit11/Deep_Learning_Pytorch/blob/main/Testing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Deep Learning with Pytorch notebook 1

In [1]:
import torch

In [2]:
torch.__version__

'2.6.0+cu124'

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim # Check number of dimensions

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape # Check shape

torch.Size([2])

In [9]:
MATRIX=torch.tensor([[7,8],
                     [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim # Check number of dimensions

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
tensor1 =torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
tensor1

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
tensor1.ndim

3

In [16]:
tensor1.shape

torch.Size([1, 3, 3])